Temel.Nortwind.MVCUI/Models/CategoryListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Temel.Nortwind.Entities.Concrete;

namespace Temel.Nortwind.MVCUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; internal set; }
        public int CurrentCategory { get; internal set; }
    }
}

Temel.Nortwind.MVCUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Temel.Nortwind.Entities.Concrete;

namespace Temel.Nortwind.MVCUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; internal set; }
        public int PageCount { get; internal set; }
        public int PageSize { get; internal set; }
        public int CurrtentCategory { get; internal set; }
        public int CurrentPage { get; internal set; }
    }
}

Temel.Nortwind.MVCUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Temel.Nortwind.Business.Abstract;
using Temel.Nortwind.Business.Concrete;
using Temel.Nortwind.MVCUI.Services;

namespace Temel.Nortwind.MVCUI.Controllers
{
    public class CartController:Controller
    {
        private ICartServiceSession CartSessionService;
        private ICartService cartService;
        private IProductService productSevice;
        public CartController(ICartServiceSession CartSessionService, ICartService cartService, IProductService productSevice)
        {
            this.CartSessionService = CartSessionService;
            this.cartService = cartService;
            this.productSevice = productSevice;
        }
        public ActionResult AddToCart(int productId)
        {
            var productToBeAdded = productSevice.GetById(productId);

            var cart = CartSessionService.GetCart();
            cartService.AddToCart(cart, productToBeAdded);
            CartSessionService.SetCart(cart);
            TempData.Add("message",String.Format("Your product,{0}, was succesfully added to cart",productToBeAdded.ProductName));
            return RedirectToAction("Index", "Product");
        }


    }
}

Temel.Nortwind.MVCUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Temel.Nortwind.Business.Abstract;
using Temel.Nortwind.MVCUI.Models;

namespace Temel.Nortwind.MVCUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int page = 1,int Category=0)
        { int pageSize = 10;
            var products = Category == 0 ? _productService.GetAll() : _productService.GetByCategory(Category);
            ProductListViewModel model = new ProductListViewModel
            {

                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count / (double)pageSize),
                PageSize = pageSize,
                CurrtentCategory = Category,
                CurrentPage = page
            };


            return View(model);
        }
        //public IActionResult AddToCart()
        //{

        //}
        
    }
}

Temel.Nortwind.MVCUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Temel.Nortwind.Business.Abstract;
using Temel.Nortwind.MVCUI.Models;

namespace Temel.Nortwind.MVCUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public ViewViewComponentResult Invoke()
        {

            var model = new CategoryListViewModel {
                Categories = _categoryService.GetAll(),
            CurrentCategory =Convert.ToInt32( HttpContext.Request.Query["category"])
            };
            return View(model);

        }
    }
}

Temel.Nortwind.MVCUI/Views/Product/Index.cshtml
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@{
    Layout = "~/Views/_Layout.cshtml";
    ViewData["Title"] = "Index";
}



<div>
    <table class="table table-responsive">
        <tr>
            <td>Prdocut Name</td>
            <td>Unit Price</td>
            <td>UnitinStock</td>

        </tr>
        @foreach (var product in Model.Products)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
                <td><a class="btn btn-xs btn-success"  href="/Cart/AddToCart?productId=@product.ProductId">Add to Cart</a></td>
            </tr>
        }
    </table>
</div>
<product-list-pager current-page="@Model.CurrentPage" current-category="@Model.CurrtentCategory" page-count="@Model.PageCount" page-size="@Model.PageSize">

</product-list-pager>

Temel.Nortwind.MVCUI/Views/Shared/Components/CategoryList/Default.cshtml
@model Temel.Nortwind.MVCUI.Models.CategoryListViewModel

@{
    ViewData["Title"] = "View";
}

<div class="list-group">
   @foreach(var category in Model.Categories)
   {
       var css = "list-group-item ";
       if (category.CategoryId == Model.CurrentCategory)
       {
           css +="active";
       }
    <a class="@css" href="/product/index?category=@category.CategoryId">@category.CategoryName</a>
   }

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Temel.Nortwind.MVCUI/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>


    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>
    <div class="col-md-12">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">NorthWind</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Link</a></li>
                      
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                     
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class=" col-md-2">@await Component.InvokeAsync("CategoryList")</div>
    <div class="col-md-10">
        @if (TempData["message"] != null)
        {
        <div class="alert alert-info" role="alert">@TempData["message"]</div>
        }
        @RenderBody() 
    </div>
</body>
</html>